openapi: 3.0.3
info:
  title: Social Network API (Write Operations)
  version: 1.0.0

paths:
  /users/{user_id}/posts:
    post:
      summary: Create a new post
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
          description: ID of the user creating the post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text, images, location]
              properties:
                text:
                  type: string
                images:
                  type: array
                  items:
                    type: object
                    required: [id, url]
                    properties:
                      id:
                        type: string
                      url:
                        type: string
                location:
                  type: object
                  required: [latitude, longitude]
                  properties:
                    latitude:
                      type: number
                      format: float
                    longitude:
                      type: number
                      format: float
      responses:
        '201':
          description: Post created
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /posts/{post_id}:
    put:
      summary: Update a post
      parameters:
        - in: path
          name: post_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                images:
                  type: array
                  items:
                    type: object
                    required: [id, url]
                    properties:
                      id:
                        type: string
                      url:
                        type: string
                location:
                  type: object
                  properties:
                    latitude:
                      type: number
                      format: float
                    longitude:
                      type: number
                      format: float
      responses:
        '200':
          description: Post updated
        '400':
          description: Invalid input
        '500':
          description: Internal server error

    delete:
      summary: Delete a post
      parameters:
        - in: path
          name: post_id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Post deleted
        '400':
          description: Invalid post ID
        '500':
          description: Internal server error

  /posts/{post_id}/comments:
    post:
      summary: Create a comment on a post
      parameters:
        - in: path
          name: post_id
          required: true
          schema:
            type: string
          description: ID of the post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id, text]
              properties:
                user_id:
                  type: string
                text:
                  type: string
      responses:
        '201':
          description: Comment created
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /comments/{comment_id}:
    put:
      summary: Update a comment
      parameters:
        - in: path
          name: comment_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [text]
              properties:
                text:
                  type: string
      responses:
        '200':
          description: Comment updated
        '400':
          description: Invalid input
        '500':
          description: Internal server error

    delete:
      summary: Delete a comment
      parameters:
        - in: path
          name: comment_id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Comment deleted
        '400':
          description: Invalid comment ID
        '500':
          description: Internal server error

  /posts/{post_id}/likes:
    post:
      summary: Add a like to a post
      parameters:
        - in: path
          name: post_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [user_id]
              properties:
                user_id:
                  type: string
      responses:
        '201':
          description: Like added
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /posts/{post_id}/likes/{user_id}:
    delete:
      summary: Remove like from a post
      parameters:
        - in: path
          name: post_id
          required: true
          schema:
            type: string
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Like removed
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /users/{user_id}/subscriptions:
    post:
      summary: Subscribe to another user
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [target_user_id]
              properties:
                target_user_id:
                  type: string
      responses:
        '201':
          description: Subscription created
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /users/{user_id}/subscriptions/{target_user_id}:
    delete:
      summary: Unsubscribe from a user
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
        - in: path
          name: target_user_id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Subscription removed
        '400':
          description: Invalid input
        '500':
          description: Internal server error
